name = "chisomo-gideon-banda"
compatibility_date = "2024-02-10"

[build]
command = ""
publish = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
exclude = "/*.{jpg,jpeg,png,gif,svg,css,js,ico}"

[env.production.vars]
ENVIRONMENT = "production"
