name = "chisomo-gideon-banda"
compatibility_date = "2024-02-10"

[build]
command = ""
publish = "."

pages_build_output_dir = "portfolio-cloudflare-correct"

[env.production.vars]
ENVIRONMENT = "production"
